title = "Jason Wyckoff"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
relativeURLs = true
baseURL = "/"

[params]
address = "Franklin, TN"
email = "jason@wyckoff.io"
favicon = "/favicon.ico"
firstName = "Jason"
lastName = "Wyckoff"
phone = "1-555-555-1234"
profileImage = "img/wy-logo.png"
showEducation = false
showExperience = false

showOpenSource = false
showProjects = false
showPublications = false
showCertifications = false
showQr = true
showSkills = false

socialTitle = ""

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/jwyckoff/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jwyckoff/"
name = "GitHub"

# [[params.handles]]
# link = "https://bitbucket.org/jwyckoff/"
# name = "Bitbucket"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"